# Generated by Django 4.1 on 2022-08-23 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6c7b26c-5f45-475b-ac3d-8bb3d27aaf1b'), primary_key=True, serialize=False),
        ),
    ]
