# Generated by Django 4.1 on 2022-08-23 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b384407-f17b-41e2-b256-087c2bc62951'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7570dca7-b8b0-4a9a-93ce-cb589f5c1d91'), primary_key=True, serialize=False),
        ),
    ]
