# Generated by Django 4.1 on 2022-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_order_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_order',
        ),
    ]
