# Generated by Django 4.1 on 2022-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateField(auto_now_add=True),
        ),
    ]
