# Generated by Django 4.1 on 2022-08-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_order_date_of_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_order',
        ),
    ]
