# Generated by Django 4.1 on 2022-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.CharField(default='2022-08-23 14:43:23.162911', editable=False, max_length=20),
        ),
    ]
