# Generated by Django 4.1 on 2022-08-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_rooms',
        ),
    ]
