# Generated by Django 4.1 on 2022-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_order_ordered_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_rooms',
            field=models.ManyToManyField(to='home.room'),
        ),
    ]
