# Generated by Django 4.1 on 2022-09-03 18:52

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_userprofile_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0, validators=[home.models.is_greater_than_zero]),
        ),
    ]
