# Generated by Django 4.1 on 2022-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
