# Generated by Django 4.1 on 2022-09-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_order_check_in_date_alter_order_check_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_rooms',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.room'),
            preserve_default=False,
        ),
    ]
