# Generated by Django 4.1 on 2022-09-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
    ]
