# Generated by Django 4.1 on 2022-10-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
